name: check
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Check
      run: ./gradlew --stacktrace check embulk-input-example:gem embulk-input-example_jetty93:gem embulk-output-example:gem
